# Generated by Django 5.0.1 on 2024-02-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hos_id', models.IntegerField(default=1, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
