# Generated by Django 5.0.1 on 2024-02-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device_ID', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('respiratory_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patients_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone_number0', models.IntegerField()),
                ('phone_number1', models.IntegerField()),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=6)),
                ('device_ID', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
