# Generated by Django 5.0.1 on 2024-02-02 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Patient_Device_ID',
        ),
    ]
