# Generated by Django 5.0.1 on 2024-02-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_rename_admin_patient_device_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Patient_Device_ID',
        ),
        migrations.AddField(
            model_name='patients_details',
            name='Doc_id',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AddField(
            model_name='patients_details',
            name='Hos_id',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
