# Generated by Django 5.0.1 on 2024-02-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_user_delete_patient_device_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients_details',
            name='Doc_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='patients_details',
            name='Hos_id',
            field=models.IntegerField(default=1),
        ),
    ]
