# Generated by Django 5.0.1 on 2024-02-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_rename_admin_credentials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credentials',
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='Hos_id',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='doctordetails',
            name='Doc_id',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
