# Generated by Django 5.0.1 on 2024-02-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_delete_credentials_doctordetails_hos_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetails',
            name='Hos_id',
            field=models.IntegerField(default=1),
        ),
    ]
